services:
  radio-online-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:1034"
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./data:/app/data
    user: "node"
